/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllFile: typeof import('./src/components/study/allFile.vue')['default']
    Content: typeof import('./src/components/chat/content.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    FirstHeader: typeof import('./src/components/home/FirstHeader.vue')['default']
    FirstList: typeof import('./src/components/home/FirstList.vue')['default']
    FirstTopic: typeof import('./src/components/home/FirstTopic.vue')['default']
    Header: typeof import('./src/components/chat/header.vue')['default']
    HeartFailure: typeof import('./src/components/study/heartFailure.vue')['default']
    Iframe: typeof import('./src/components/study/iframe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondList: typeof import('./src/components/home/SecondList.vue')['default']
    Send: typeof import('./src/components/chat/send.vue')['default']
  }
}
